import type { Metadata } from "next";
import "./globals.css";
import HamburgerMobile from "@/components/HamburgerMobile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <div className="block md:hidden flex justify-end">
        <HamburgerMobile />
        </div>
      </body>
    </html>
  );
}
